import jsPDF from 'jspdf';
import html2canvas from 'html2canvas-pro';

export interface PdfExportOptions {
	reportEl: HTMLElement;
	toolName: string;
	source: string;
	filenamePrefix: string;
}

function safeSlug(source: string): string {
	const cleaned = source
		.replace(/^https?:\/\//, '')
		.replace(/[^a-z0-9]+/gi, '-')
		.replace(/(^-|-$)/g, '')
		.toLowerCase()
		.slice(0, 60);
	return cleaned || 'report';
}

// Renders the live, already-styled report DOM to a canvas and slices it across
// A4 pages with a branded header/footer, instead of hand-building a parallel PDF
// layout per tool — each tool's report shape differs enough that this stays in
// sync automatically as report markup changes.
export async function exportReportToPdf({ reportEl, toolName, source, filenamePrefix }: PdfExportOptions): Promise<void> {
	const bodyBg = getComputedStyle(document.body).backgroundColor;
	const canvas = await html2canvas(reportEl, {
		backgroundColor: bodyBg && bodyBg !== 'rgba(0, 0, 0, 0)' ? bodyBg : '#ffffff',
		scale: Math.min(2, (window.devicePixelRatio || 1) * 1.5),
		useCORS: true,
		logging: false,
	});

	const pdf = new jsPDF({ unit: 'pt', format: 'a4', compress: true });
	const pageW = pdf.internal.pageSize.getWidth();
	const pageH = pdf.internal.pageSize.getHeight();
	const margin = 28;
	const headerH = 58;
	const footerH = 24;
	const contentW = pageW - margin * 2;
	const contentH = pageH - headerH - footerH - margin;

	const pxPerPt = canvas.width / contentW;
	const sliceHeightPx = Math.max(1, Math.floor(contentH * pxPerPt));
	const totalSlices = Math.max(1, Math.ceil(canvas.height / sliceHeightPx));

	const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

	function drawHeader(pageNum: number, totalPages: number) {
		pdf.setFillColor(17, 24, 39);
		pdf.rect(0, 0, pageW, headerH, 'F');
		pdf.setTextColor(255, 255, 255);
		pdf.setFont('helvetica', 'bold');
		pdf.setFontSize(14);
		pdf.text('AISEOShift', margin, 24);
		pdf.setFont('helvetica', 'normal');
		pdf.setFontSize(10);
		pdf.text(toolName, margin, 40);
		pdf.setFontSize(8);
		pdf.setTextColor(203, 213, 225);
		const truncSource = source.length > 75 ? source.slice(0, 75) + '…' : source;
		pdf.text(truncSource, margin, 52);
		pdf.setFontSize(8);
		pdf.setTextColor(255, 255, 255);
		pdf.text(dateStr, pageW - margin, 24, { align: 'right' });
		if (totalPages > 1) {
			pdf.text(`Page ${pageNum} of ${totalPages}`, pageW - margin, 40, { align: 'right' });
		}
	}

	function drawFooter() {
		pdf.setFontSize(7.5);
		pdf.setTextColor(148, 163, 184);
		pdf.text('Generated by AISEOShift · aiseoshift.com', margin, pageH - 10);
	}

	for (let i = 0; i < totalSlices; i++) {
		if (i > 0) pdf.addPage();
		const sy = i * sliceHeightPx;
		const sh = Math.min(sliceHeightPx, canvas.height - sy);

		const sliceCanvas = document.createElement('canvas');
		sliceCanvas.width = canvas.width;
		sliceCanvas.height = sh;
		const ctx = sliceCanvas.getContext('2d')!;
		ctx.drawImage(canvas, 0, sy, canvas.width, sh, 0, 0, canvas.width, sh);
		const imgData = sliceCanvas.toDataURL('image/png');

		drawHeader(i + 1, totalSlices);
		const imgH = (sh / canvas.width) * contentW;
		pdf.addImage(imgData, 'PNG', margin, headerH + 8, contentW, imgH);
		drawFooter();
	}

	const filename = `${filenamePrefix}-${safeSlug(source)}-${new Date().toISOString().slice(0, 10)}.pdf`;
	pdf.save(filename);
}
