import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 1280, height: 900 } })).newPage();
await p.goto('http://localhost:8788/tools/keyword-density/', { waitUntil: 'networkidle' });
await p.locator('#url-input').fill('https://aiseoshift.com/blog/ai-tools-for-lawyers/');
await p.locator('#keyword-input').fill('AI tools for lawyers');
await p.locator('#analyze-btn').click();
await p.locator('.kd-focus-card').waitFor({ timeout: 30000 });
await p.waitForTimeout(500);
const items = await p.locator('.kd-reco-item').allInnerTexts();
console.log('reco count:', items.length);
items.forEach((t, i) => console.log(`  ${i+1}. ${t.split('\n').slice(0, 2).join(' — ')}`));
await b.close();
