import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const page = await ctx.newPage();
await page.goto('http://localhost:8788/tools/meta-checker/', { waitUntil: 'networkidle' });
await page.locator('#url-input').fill('https://aiseoshift.com/blog/ai-tools-for-lawyers/');
await page.locator('#analyze-btn').click();
await page.locator('.mt-report.visible').waitFor();
await page.waitForTimeout(500);
const layoutCols = await page.locator('.mt-layout').evaluate((el) => getComputedStyle(el).gridTemplateColumns);
const layoutWidth = await page.locator('.mt-layout').evaluate((el) => getComputedStyle(el).width);
const sidebarVisible = await page.locator('.mt-sidebar').isVisible();
const sidebarWidth = await page.locator('.mt-sidebar').evaluate((el) => el.getBoundingClientRect().width);
const mainWidth = await page.locator('.mt-main').evaluate((el) => el.getBoundingClientRect().width);
console.log('layout columns:', layoutCols);
console.log('layout width:', layoutWidth);
console.log('sidebar visible:', sidebarVisible, 'width:', sidebarWidth);
console.log('main width:', mainWidth);
await browser.close();
